# Generated by Django 5.1.1 on 2024-11-20 08:38

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField()),
                ('parsed_content', models.JSONField()),
                ('meta_data', models.JSONField()),
                ('open_ai_conversation', models.JSONField(default=list, null=True)),
                ('llama_conversation', models.JSONField(default=list, null=True)),
                ('dbrx_conversation', models.JSONField(default=list, null=True)),
                ('gemini_conversation', models.JSONField(default=list, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=chat.models.MyAzureStorage(), upload_to=chat.models.user_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='chat.session')),
            ],
        ),
    ]
